# Generated by Django 4.2.6 on 2023-10-27 14:35

from django.db import migrations, models
import django.db.models.deletion
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
                ('image', models.ImageField(upload_to=store.models.category_image_directory_path, verbose_name='Изображение')),
                ('activity', models.BooleanField(default=True, verbose_name='Активация')),
                ('sort_index', models.IntegerField(max_length=11, verbose_name='Индекс сортировки')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['sort_index'],
            },
        ),
    ]
