# Generated by Django 4.2.6 on 2023-10-27 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_reviews'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=False, default='', max_length=70, verbose_name='Название')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('sum_discount', models.FloatField(blank=False, verbose_name='Сумма скидки')),
                ('total_products', models.IntegerField(blank=True, verbose_name='Количество товаров')),
                ('valid_from', models.DateTimeField(blank=True, verbose_name='Действует с')),
                ('valid_to', models.DateTimeField(blank=False, verbose_name='Действует до')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
            ],
            options={
                'verbose_name': 'Скидка',
                'verbose_name_plural': 'Скидки',
                'db_table': 'Discounts',
                'ordering': ['id', 'name'],
            },
        ),
    ]
