# Generated by Django 4.2.6 on 2023-10-30 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0001_initial'),
        ('store', '0004_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offer',
            name='seller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='authorization.profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.ManyToManyField(related_name='discounts', to='store.discount', verbose_name='Скидка'),
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(related_name='products', to='store.tag', verbose_name='Теги'),
        ),
        migrations.AlterField(
            model_name='category',
            name='sort_index',
            field=models.IntegerField(verbose_name='Индекс сортировки'),
        ),
    ]
