# Generated by Django 4.2.6 on 2023-10-30 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='total_products',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество товаров'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='valid_from',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Действует с'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='availability',
            field=models.BooleanField(default=False, verbose_name='Доступность'),
        ),
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.ImageField(
                blank=True, null=True, upload_to='products/product/%y/%m/%d/', verbose_name='Изображение'
            ),
        ),
    ]
