# Generated by Django 4.2.6 on 2023-11-09 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_category_options_alter_orders_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banners',
            name='images',
        ),
        migrations.AddField(
            model_name='banners',
            name='product',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.product', verbose_name='Продукт'),
            preserve_default=False,
        ),
    ]
