# Generated by Django 4.2.6 on 2023-11-10 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_remove_banners_images_banners_product'),
        ('store', '0013_remove_product_reviews_reviews_product'),
    ]

    operations = [
    ]
