# Generated by Django 4.2.6 on 2023-11-11 19:31

from django.db import migrations
import imagekit.models.fields
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_rename_images_product_preview_product_is_view_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='preview',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='products/product/%y/%m/%d/', verbose_name='Основное фото'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to=store.models.product_images_directory_path, verbose_name='Фотография товара'),
        ),
    ]
