# Generated by Django 4.2.6 on 2023-11-17 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_alter_product_preview_alter_productimage_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orders',
            options={'verbose_name': 'Заказ'},
        ),
    ]
