# Generated by Django 4.2.6 on 2023-11-28 13:43

from django.db import migrations, models
import django.db.models.deletion
import store.utils


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0003_remove_profile_sale_alter_profile_avatar_and_more'),
        ('store', '0017_alter_orders_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orders',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_view',
        ),
        migrations.AlterField(
            model_name='offer',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='store.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='authorization.profile', verbose_name='Продавец'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.JSONField(default=store.utils.jsonfield_default_description, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='feature',
            field=models.JSONField(default=store.utils.jsonfield_default_feature, verbose_name='Характеристика'),
        ),
    ]
