# Generated by Django 4.2.6 on 2023-12-08 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_alter_orders_options_remove_product_is_view_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='total',
            new_name='total_payment',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='address',
        ),
        migrations.AddField(
            model_name='category',
            name='discount',
            field=models.ManyToManyField(related_name='categories', to='store.discount', verbose_name='Скидка'),
        ),
        migrations.AddField(
            model_name='discount',
            name='priority',
            field=models.BooleanField(default=False, verbose_name='Приоритет'),
        ),
        migrations.AddField(
            model_name='discount',
            name='sum_cart',
            field=models.FloatField(blank=True, null=True, verbose_name='Сумма корзины'),
        ),
        migrations.AddField(
            model_name='orders',
            name='payment',
            field=models.IntegerField(choices=[(None, 'Выберите оплату'), (1, 'Онлайн картой'), (2, 'Онлайн со случайного счета')], default=1, verbose_name='Способ оплаты'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orders',
            name='delivery_type',
            field=models.IntegerField(choices=[(None, 'Выберите доставку'), (1, 'Обычная доставка'), (2, 'Экспресс-доставка')], verbose_name='Способ доставки'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.IntegerField(choices=[('1', 'Оплачено'), ('2', 'Не оплачено'), ('3', 'Доставляется')], verbose_name='Статус заказа'),
        ),
    ]
