# Generated by Django 4.2.6 on 2023-12-15 02:39

from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_remove_product_feature_orders_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='limited_edition',
            field=models.BooleanField(default=False, verbose_name='Ограниченный тираж'),
        ),
        migrations.CreateModel(
            name='BannersCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preview', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='category/%y/%m/%d/', verbose_name='Фото категории')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активный')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.category', verbose_name='Категории')),
            ],
            options={
                'verbose_name': 'Банер категории',
                'verbose_name_plural': 'Банеры категорий',
                'db_table': 'Banners_Category',
            },
        ),
    ]
