# Generated by Django 4.2.6 on 2024-01-22 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0008_alter_profile_slug'),
        ('store', '0023_orders_archived_alter_banners_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='authorization.profile', verbose_name='Профиль'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authorization.profile', verbose_name='Автор'),
        ),
    ]
