# Generated by Django 4.2.6 on 2024-01-22 15:16

from django.db import migrations, models
import store.utils


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_alter_orders_profile_alter_reviews_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='banners',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Описание баннера'),
        ),
        migrations.AddField(
            model_name='banners',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание баннера'),
        ),
        migrations.AddField(
            model_name='banners',
            name='title_en',
            field=models.CharField(db_index=True, max_length=150, null=True, verbose_name='Название баннера'),
        ),
        migrations.AddField(
            model_name='banners',
            name='title_ru',
            field=models.CharField(db_index=True, max_length=150, null=True, verbose_name='Название баннера'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='discount',
            name='description_en',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='discount',
            name='description_ru',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='discount',
            name='title_en',
            field=models.CharField(default='', max_length=70, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='discount',
            name='title_ru',
            field=models.CharField(default='', max_length=70, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='orders',
            name='status_exception_en',
            field=models.TextField(blank=True, null=True, verbose_name='Статус ошибки'),
        ),
        migrations.AddField(
            model_name='orders',
            name='status_exception_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Статус ошибки'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.JSONField(default=store.utils.jsonfield_default_description, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ru',
            field=models.JSONField(default=store.utils.jsonfield_default_description, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(db_index=True, default='', max_length=150, null=True, verbose_name='Название товара'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ru',
            field=models.CharField(db_index=True, default='', max_length=150, null=True, verbose_name='Название товара'),
        ),
    ]
