# Generated by Django 4.2.6 on 2023-10-30 11:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0004_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('sale', models.IntegerField()),
                ('avatar', models.ImageField(upload_to='')),
                ('name_store', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('role', models.CharField(default='user', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('viewed_orders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
                'db_table': 'Profiles',
                'ordering': ['id', 'user'],
                'permissions': (('store', 'has offers for sale'), ('user', 'all site users'), ('buyer', 'only buys goods'), ('admin', 'manages the site')),
            },
        ),
    ]
