# Generated by Django 4.2.6 on 2023-11-05 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_reviews_author'),
        ('authorization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='sale',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='viewed_orders',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.product'),
        ),
    ]
