# Generated by Django 4.2.6 on 2023-11-21 16:35

from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0002_alter_profile_sale_alter_profile_viewed_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='sale',
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='profiles/profile/%y/%m/%d/', verbose_name='Фотография товара'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name_store',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('store', 'Store'), ('buyer', 'Buyer')], default='buyer'),
        ),
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_type', models.IntegerField(choices=[(None, 'Выберите доставку'), (1, 'Обычная доставка'), (2, 'Экспресс-доставка')], verbose_name='Способ доставки')),
                ('payment', models.IntegerField(choices=[(None, 'Выберите оплату'), (1, 'Онлайн картой'), (2, 'Онлайн со случайного счета')], verbose_name='Способ оплаты')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='store_settings', to='authorization.profile')),
            ],
            options={
                'verbose_name': 'Настройки магазина',
                'verbose_name_plural': 'Настройки магазина',
                'db_table': 'StoreSettings',
                'ordering': ['id', 'profile'],
            },
        ),
    ]
