# Generated by Django 4.2.6 on 2023-12-14 21:29

import authorization.models
from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0005_alter_profile_avatar_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=authorization.models.profile_images_directory_path, verbose_name='Фотография профиля'),
        ),
    ]
