# Generated by Django 4.2.6 on 2023-12-21 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0007_profile_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=150, null=True, verbose_name='Слаг'),
        ),
    ]
