# Generated by Django 4.2.6 on 2023-12-05 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractCharacteristicModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('made_in', models.CharField(blank=True, max_length=30, null=True, verbose_name='Сделан в ')),
                ('production_year', models.IntegerField(blank=True, null=True, verbose_name='В каком году произведен')),
                ('color', models.CharField(blank=True, max_length=15, null=True, verbose_name='Цвет')),
                ('weight', models.CharField(blank=True, null=True, verbose_name='Вес')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='HeadphonesCharacteristic',
            fields=[
                ('abstractcharacteristicmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='compare.abstractcharacteristicmodel')),
                ('wireless', models.CharField(default='Нет', max_length=20, verbose_name='Беспроводные')),
                ('mic', models.CharField(default='Нет', max_length=20, verbose_name='Микрофон')),
                ('fit', models.CharField(max_length=20, verbose_name='Как носить')),
                ('bluetooth', models.CharField(default='Нет', max_length=20, verbose_name='Наличие Bluetooth')),
                ('resistance', models.IntegerField(blank=True, null=True, verbose_name='Сопротивление (Ом)')),
                ('hdmi', models.CharField(default='Нет', max_length=20, verbose_name='HDMI')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Дополнительное описание')),
            ],
            bases=('compare.abstractcharacteristicmodel',),
        ),
        migrations.CreateModel(
            name='KitchenCharacteristic',
            fields=[
                ('abstractcharacteristicmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='compare.abstractcharacteristicmodel')),
                ('type', models.CharField(blank=True, max_length=20, verbose_name='Тип техники')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Дополнительное описание')),
            ],
            bases=('compare.abstractcharacteristicmodel',),
        ),
        migrations.CreateModel(
            name='MicrowaveOvenCharacteristic',
            fields=[
                ('abstractcharacteristicmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='compare.abstractcharacteristicmodel')),
                ('capacity', models.IntegerField(blank=True, null=True, verbose_name='Объём загрузки')),
                ('power', models.IntegerField(blank=True, null=True, verbose_name='Мощность Вт')),
                ('grill', models.CharField(default='Информации нет', max_length=20)),
                ('height', models.IntegerField(blank=True, null=True, verbose_name='Высота')),
                ('width', models.IntegerField(blank=True, null=True, verbose_name='Ширина')),
                ('depth', models.IntegerField(blank=True, null=True, verbose_name='Глубина')),
            ],
            bases=('compare.abstractcharacteristicmodel',),
        ),
        migrations.CreateModel(
            name='MobileCharacteristic',
            fields=[
                ('abstractcharacteristicmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='compare.abstractcharacteristicmodel')),
                ('phone_type', models.CharField(max_length=20, verbose_name='Тип мобильного телефона')),
                ('screen_size', models.IntegerField(blank=True, null=True, verbose_name='Размер экрана в дюймах')),
                ('screen_resolution', models.CharField(blank=True, null=True, verbose_name='Разрешение экрана')),
                ('screen_technology', models.CharField(blank=True, max_length=10, null=True, verbose_name='Технология экрана')),
                ('op_system', models.CharField(default='Информации нет', max_length=20, verbose_name='Операционная система')),
            ],
            bases=('compare.abstractcharacteristicmodel',),
        ),
        migrations.CreateModel(
            name='NotebookCharacteristic',
            fields=[
                ('abstractcharacteristicmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='compare.abstractcharacteristicmodel')),
                ('laptop_type', models.CharField(default='Информации нет', max_length=20, verbose_name='Тип ноутбука')),
                ('screen_size', models.IntegerField(blank=True, null=True, verbose_name='Размер экрана в дюймах')),
                ('screen_resolution', models.CharField(blank=True, null=True, verbose_name='Разрешение экрана')),
                ('ppi', models.IntegerField(blank=True, null=True, verbose_name='Плотность пикселей')),
                ('op_system', models.CharField(default='Информации нет', max_length=20, verbose_name='Операционная система')),
                ('op_version', models.CharField(blank=True, max_length=15, null=True, verbose_name='Версия операционной системы')),
            ],
            bases=('compare.abstractcharacteristicmodel',),
        ),
        migrations.CreateModel(
            name='PhotoCamCharacteristic',
            fields=[
                ('abstractcharacteristicmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='compare.abstractcharacteristicmodel')),
                ('type', models.CharField(default='Информации нет', max_length=30, verbose_name='Тип фотоаппарата')),
                ('mp', models.IntegerField(blank=True, null=True, verbose_name='Количество мегапикселей')),
                ('max_iso', models.IntegerField(blank=True, null=True, verbose_name='ISO максимальная')),
                ('min_iso', models.IntegerField(blank=True, null=True, verbose_name='ISO минимальная')),
                ('video_resolution', models.IntegerField(blank=True, null=True, verbose_name='Видео разрешение')),
            ],
            bases=('compare.abstractcharacteristicmodel',),
        ),
        migrations.CreateModel(
            name='TorchereCharacteristic',
            fields=[
                ('abstractcharacteristicmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='compare.abstractcharacteristicmodel')),
                ('led_type', models.CharField(blank=True, max_length=20, null=True, verbose_name='Тип лампочки')),
                ('height', models.IntegerField(blank=True, null=True, verbose_name='Высота')),
            ],
            bases=('compare.abstractcharacteristicmodel',),
        ),
        migrations.CreateModel(
            name='TVSetCharacteristic',
            fields=[
                ('abstractcharacteristicmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='compare.abstractcharacteristicmodel')),
                ('name', models.TextField(blank=True, default='TVSet', null=True)),
                ('screen', models.CharField(blank=True, max_length=10, null=True, verbose_name='Размер экрана')),
                ('resolution', models.CharField(blank=True, max_length=10, null=True, verbose_name='Разрешение экрана')),
                ('country', models.CharField(blank=True, max_length=25, null=True, verbose_name='Страна производитель')),
                ('freq', models.IntegerField(blank=True, null=True, verbose_name='Частота обновления')),
                ('wi_fi', models.CharField(default='Нет', max_length=20, verbose_name='Наличие Wi-Fi')),
                ('hdmi', models.CharField(default='Нет', max_length=20, verbose_name='HDMI')),
                ('description', models.TextField(verbose_name='Дополнительное описание')),
            ],
            bases=('compare.abstractcharacteristicmodel',),
        ),
        migrations.CreateModel(
            name='WashMachineCharacteristic',
            fields=[
                ('abstractcharacteristicmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='compare.abstractcharacteristicmodel')),
                ('height', models.IntegerField(blank=True, null=True, verbose_name='Высота')),
                ('width', models.IntegerField(blank=True, null=True, verbose_name='Ширина')),
                ('depth', models.IntegerField(blank=True, null=True, verbose_name='Глубина')),
                ('type_loading', models.CharField(default='Информации нет', max_length=20, verbose_name='Тип загрузки')),
                ('capacity', models.IntegerField(blank=True, null=True, verbose_name='Объём загрузки')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Дополнительное описание')),
            ],
            bases=('compare.abstractcharacteristicmodel',),
        ),
    ]
