# Generated by Django 4.2.6 on 2023-12-08 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectroCharacteristic',
            fields=[
                ('abstractcharacteristicmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='compare.abstractcharacteristicmodel')),
                ('type_product', models.CharField(default='Информации нет', max_length=20, verbose_name='Тип электроники')),
                ('power', models.CharField(blank=True, max_length=30, null=True, verbose_name='Тип питания')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Дополнительное описание')),
            ],
            bases=('compare.abstractcharacteristicmodel',),
        ),
        migrations.AddField(
            model_name='torcherecharacteristic',
            name='place_type',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Место расположения'),
        ),
        migrations.AlterField(
            model_name='microwaveovencharacteristic',
            name='grill',
            field=models.CharField(default='Информации нет', max_length=30),
        ),
    ]
