# Generated by Django 4.2.6 on 2023-11-17 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_alter_orders_options'),
        ('cart', '0002_alter_cart_options_remove_cart_slug_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ['-created_at'], 'verbose_name': 'корзина', 'verbose_name_plural': 'корзину'},
        ),
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
        migrations.AddField(
            model_name='cart',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.orders', verbose_name='Пользователь'),
            preserve_default=False,
        ),
    ]
