# Generated by Django 4.2.6 on 2023-11-20 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_alter_orders_options'),
        ('cart', '0003_alter_cart_options_remove_cart_user_cart_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ['-created_at'], 'verbose_name': 'корзину', 'verbose_name_plural': 'корзины'},
        ),
        migrations.AlterField(
            model_name='cart',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.orders', verbose_name='Заказ'),
        ),
    ]
